<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Course;
use App\Models\User;

class MockCourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Asegurar que exista al menos una categoría
        $categoryId = DB::table('categories')->insertGetId([
            'name' => 'Programación',
            'description' => 'Cursos de desarrollo de software',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // 2. Asegurar que exista al menos un instructor para asignarle los cursos
        $instructor = User::firstOrCreate(
            ['email' => 'instructor@lumina.com'],
            [
                'role_id' => 3, // Instructor
                'name' => 'Carlos López',
                'password' => bcrypt('password123'),
                'email_verified_at' => now(),
                'is_active' => true,
            ]
        );

        $courses = [
            [
                'title' => 'Angular Avanzado: Patrones y RxJS',
                'description' => 'En este curso aprenderás a estructurar aplicaciones Angular escalables, implementar patrones de diseño modernos y dominar el uso de RxJS.',
                'duration' => 12,
                'level' => 'advanced',
                'price' => 49.99,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Introducción a React y Hooks',
                'description' => 'Descubre el ecosistema de React, aprende a crear componentes reutilizables, manejar el estado con Hooks y gestionar efectos secundarios.',
                'duration' => 8,
                'level' => 'beginner',
                'price' => 29.99,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Node.js y Microservicios',
                'description' => 'Aprende a diseñar y construir APIs robustas con Node.js, Express y MongoDB. Descubre cómo dividir un monolito en microservicios.',
                'duration' => 20,
                'level' => 'advanced',
                'price' => 59.99,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fundamentos de Python',
                'description' => 'Aprende a programar desde cero con Python. Veremos estructuras de datos, control de flujo, funciones, POO.',
                'duration' => 10,
                'level' => 'beginner',
                'price' => 19.99,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Diseño UX/UI para Desarrolladores',
                'description' => 'Curso práctico donde aprenderás los principios del diseño de interfaces y experiencia de usuario. Aprenderás a usar Figma.',
                'duration' => 6,
                'level' => 'intermediate',
                'price' => 39.99,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'DevOps y CI/CD con GitHub Actions',
                'description' => 'Aprende las mejores prácticas de integración y entrega continua (CI/CD) utilizando GitHub Actions.',
                'duration' => 15,
                'level' => 'intermediate',
                'price' => 54.99,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mastering TypeScript',
                'description' => 'Domina los conceptos avanzados de TypeScript: genéricos, tipos condicionales, decoradores y utility types.',
                'duration' => 9,
                'level' => 'intermediate',
                'price' => 44.99,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Machine Learning Básico',
                'description' => 'Un curso introductorio donde aprenderás a entrenar tus primeros modelos de regresión y clasificación usando Scikit-Learn.',
                'duration' => 25,
                'level' => 'advanced',
                'price' => 69.99,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cursor',
                'description' => 'Domina el uso de Cursor, el editor de código potenciado por IA.',
                'duration' => 10,
                'level' => 'intermediate',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Affinity Studio',
                'description' => 'Aprende a dominar Affinity Designer, Photo y Publisher.',
                'duration' => 12,
                'level' => 'intermediate',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Next.js',
                'description' => 'Aprende a construir aplicaciones web ultra rápidas y escalables con Next.js 14.',
                'duration' => 18,
                'level' => 'intermediate',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Figma Avanzado',
                'description' => 'Crea interfaces escalables usando Design Systems en Figma.',
                'duration' => 9,
                'level' => 'advanced',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Docker & Kubernetes',
                'description' => 'Aprende a contenerizar tus aplicaciones con Docker y orquestarlas a gran escala con Kubernetes.',
                'duration' => 20,
                'level' => 'advanced',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1667372393913-5d5f89e62394?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Angular 18',
                'description' => 'Domina el nuevo Angular con Signals, Standalone Components, y el nuevo control flow.',
                'duration' => 16,
                'level' => 'intermediate',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Node.js con NestJS',
                'description' => 'Desarrolla APIs robustas usando NestJS, TypeORM, y bases de datos relacionales.',
                'duration' => 22,
                'level' => 'advanced',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'TailwindCSS',
                'description' => 'Olvídate del CSS tradicional. Aprende a crear interfaces complejas y responsivas.',
                'duration' => 8,
                'level' => 'beginner',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cybersecurity',
                'description' => 'Conviértete en un experto en ciberseguridad. Aprende a detectar vulnerabilidades.',
                'duration' => 30,
                'level' => 'advanced',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'React Native',
                'description' => 'Usa tus conocimientos de React para construir aplicaciones móviles nativas para iOS y Android.',
                'duration' => 20,
                'level' => 'intermediate',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Rust Programming',
                'description' => 'Descubre el lenguaje que está revolucionando la programación de sistemas.',
                'duration' => 24,
                'level' => 'advanced',
                'price' => 0,
                'category_id' => $categoryId,
                'instructor_id' => $instructor->id,
                'thumbnail_url' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('courses')->insert($courses);
    }
}
